databases:
  - name: vagas-db
    plan: free
    databaseName: vagas
    user: vagas

services:
  - type: web
    name: vagas-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app -w 2 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vagas-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0
